USE Tummi_db;
INSERT INTO Bookmark VALUES (333, 'Taste of Italy');
INSERT INTO Bookmark VALUES (393, 'Sizzling Steaks');
INSERT INTO Bookmark VALUES (746, 'Sizzling Steaks');
INSERT INTO Bookmark VALUES (935, 'Taste of Italy');
INSERT INTO Bookmark VALUES (801, 'Seafood Sensations');
INSERT INTO Bookmark VALUES (121, 'Seafood Sensations');
INSERT INTO Bookmark VALUES (734, 'Taste of Italy');
INSERT INTO Bookmark VALUES (12, 'The Rusty Spoon');
INSERT INTO Bookmark VALUES (795, 'Flavors of France');
INSERT INTO Bookmark VALUES (755, 'Sizzling Steaks');
INSERT INTO Bookmark VALUES (12, 'Seafood Sensations');
INSERT INTO Bookmark VALUES (869, 'Taste of Italy');
INSERT INTO Bookmark VALUES (327, 'The Rusty Spoon');
INSERT INTO Bookmark VALUES (325, 'Seafood Sensations');
INSERT INTO Bookmark VALUES (1, 'Seafood Sensations');
INSERT INTO Bookmark VALUES (393, 'Seafood Sensations');
INSERT INTO Bookmark VALUES (393, 'Taste of Italy');
INSERT INTO Bookmark VALUES (535, 'Culinary Delights');
INSERT INTO Bookmark VALUES (697, 'Taste of Italy');
INSERT INTO Bookmark VALUES (705, 'Flavors of France');
INSERT INTO Bookmark VALUES (935, 'Flavors of France');
INSERT INTO Bookmark VALUES (705, 'Seafood Sensations');
INSERT INTO Bookmark VALUES (17, 'The Rusty Spoon');
INSERT INTO Bookmark VALUES (333, 'Sizzling Steaks');
INSERT INTO Bookmark VALUES (801, 'Taste of Italy');
INSERT INTO Bookmark VALUES (737, 'Sizzling Steaks');
INSERT INTO Bookmark VALUES (1, 'Culinary Delights');
INSERT INTO Bookmark VALUES (801, 'Seafood Sensation');
INSERT INTO Bookmark VALUES (838, 'Taste of Italy');
INSERT INTO Bookmark VALUES (240, 'Flavors of France');
INSERT INTO Bookmark VALUES (685, 'Sizzling Steaks');
INSERT INTO Bookmark VALUES (705, 'The Rusty Spoon');
INSERT INTO Bookmark VALUES (41, 'Seafood Sensations');
INSERT INTO Bookmark VALUES (240, 'Taste of Italy');
INSERT INTO Bookmark VALUES (746, 'Culinary Delights');
INSERT INTO Bookmark VALUES (41, 'Taste of Italy');
INSERT INTO Bookmark VALUES (349, 'Sizzling Steaks');
INSERT INTO Bookmark VALUES (675, 'Culinary Delights');
INSERT INTO Bookmark VALUES (358, 'Taste of Italy');
INSERT INTO Bookmark VALUES (755, 'Culinary Delights');
INSERT INTO Bookmark VALUES (121, 'Seafood Sensation');
INSERT INTO Bookmark VALUES (460, 'Flavors of France');
INSERT INTO Bookmark VALUES (546, 'Seafood Sensations');
INSERT INTO Bookmark VALUES (349, 'Taste of Italy');
INSERT INTO Bookmark VALUES (737, 'Taste of Italy');
INSERT INTO Bookmark VALUES (561, 'Seafood Sensation');
INSERT INTO Bookmark VALUES (561, 'Culinary Delights');
INSERT INTO Bookmark VALUES (41, 'The Rusty Spoon');
INSERT INTO Bookmark VALUES (361, 'Culinary Delights');
INSERT INTO Bookmark VALUES (418, 'Seafood Sensations');
INSERT INTO Bookmark VALUES (795, 'Sizzling Steaks');
INSERT INTO Bookmark VALUES (685, 'Culinary Delights');
INSERT INTO Bookmark VALUES (734, 'Flavors of France');
INSERT INTO Bookmark VALUES (735, 'Taste of Italy');
INSERT INTO Bookmark VALUES (735, 'Flavors of France');
INSERT INTO Bookmark VALUES (325, 'Taste of Italy');
INSERT INTO Bookmark VALUES (349, 'Culinary Delights');
INSERT INTO Bookmark VALUES (561, 'Seafood Sensations');
INSERT INTO Bookmark VALUES (240, 'Taste of China');
INSERT INTO Bookmark VALUES (546, 'Flavors of France');
INSERT INTO Bookmark VALUES (17, 'The Rust Spoon');
INSERT INTO Bookmark VALUES (418, 'Seafood Sensation');
INSERT INTO Bookmark VALUES (349, 'Culinary Delight');
INSERT INTO Bookmark VALUES (935, 'Culinary Delight');
INSERT INTO Bookmark VALUES (697, 'Culinary Delight');
INSERT INTO Bookmark VALUES (564, 'Sizzling Steak');
INSERT INTO Bookmark VALUES (240, 'Seafood Sensation');
INSERT INTO Bookmark VALUES (1, 'Sizzling Steaks');
INSERT INTO Bookmark VALUES (333, 'Seafood Sensations');
INSERT INTO Bookmark VALUES (675, 'Taste of Italy');
INSERT INTO Bookmark VALUES (460, 'Seafood Sensations');
INSERT INTO Bookmark VALUES (358, 'Culinary Delights');
INSERT INTO Bookmark VALUES (705, 'Taste of Italy');
INSERT INTO Bookmark
VALUES (1, 'El Jefes'),
      (5, 'Table Mercato');